version: "3"

networks:
  default:
  gateway:
    external:
      name: traefik_webgateway

services:
  builder:
    build:
      args:
        requirements_file: production.txt
    environment:
      ENV: production  

  backend:
    command: uwsgi --ini /app/backend/config/uwsgi/uwsgi.ini
    environment:
      ENV: production
  nginx:
    image: nginx:1.13
    volumes:      
      - ./containers/nginx/conf.d/production.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html/frontend
      - web-static:/usr/share/nginx/html/static
      - web-media:/usr/share/nginx/html/media      
    labels:
      - "traefik.backend=legal_shield"
      - "traefik.docker.network=traefik_webgateway"      
      - "traefik.frontend.rule=Host:legal_shield.com.br,api.legal_shield.com.br"
      - "traefik.enable=true"
    networks:
      - gateway
      - default      