# Generated by Django 2.1.5 on 2019-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitteSearchSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_to_search', models.CharField(max_length=255, verbose_name='Key to search')),
            ],
        ),
    ]
