# Generated by Django 2.1.5 on 2019-01-11 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_twittesearchsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=255, verbose_name='Consumer Key')),
                ('consumer_secret', models.CharField(max_length=255, verbose_name='Consumer secret')),
                ('access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('access_token_secret', models.CharField(max_length=255, verbose_name='Access Token Secret')),
            ],
        ),
    ]
