# Generated by Django 2.1.5 on 2019-01-11 21:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_twittersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitte',
            name='twitte_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='Twitte Json'),
        ),
    ]
