# Generated by Django 2.1.5 on 2019-01-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_twitte_twitte_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitte',
            name='ask_donation',
            field=models.BooleanField(default=False, verbose_name='Ask Donation'),
        ),
        migrations.AddField(
            model_name='twitte',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Checked'),
        ),
        migrations.AddField(
            model_name='twitte',
            name='donated_blood',
            field=models.BooleanField(default=False, verbose_name='Donated blood'),
        ),
        migrations.AddField(
            model_name='twitte',
            name='intention_to_blood_donation',
            field=models.BooleanField(default=False, verbose_name='Intentio to blood donation'),
        ),
        migrations.AddField(
            model_name='twitte',
            name='invalid',
            field=models.BooleanField(default=False, verbose_name='Invalid'),
        ),
    ]
