# Generated by Django 2.1.5 on 2019-01-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20190111_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitte',
            name='ask_donation',
        ),
        migrations.RemoveField(
            model_name='twitte',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='twitte',
            name='donated_blood',
        ),
        migrations.RemoveField(
            model_name='twitte',
            name='intention_to_blood_donation',
        ),
        migrations.RemoveField(
            model_name='twitte',
            name='invalid',
        ),
        migrations.AddField(
            model_name='twitte',
            name='category',
            field=models.CharField(blank=True, choices=[('ASK_DONATION', 'Peiu doação'), ('DONATED_BLOOD', 'Doou sangue'), ('INTENTION_TO_BLOOD_DONATION', 'Tem intenção de doar'), ('INVALID', 'Inválido')], max_length=255, null=True, verbose_name='Category'),
        ),
    ]
